//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_app_company.AppDataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class companyEntities : DbContext
    {
        private static companyEntities _context;
        public companyEntities()
            : base("name=companyEntities")
        {
        }
            public static companyEntities GetContext()
        {
            if (_context == null)
                _context = new companyEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dogovor> dogovor { get; set; }
        public virtual DbSet<klient> klient { get; set; }
        public virtual DbSet<sotrudniki> sotrudniki { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
