//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_app_company.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int id_zakaz { get; set; }
        public Nullable<int> id_sotrudnik { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<int> id_dogovor { get; set; }
        public Nullable<int> id_uslugi { get; set; }
    
        public virtual dogovor dogovor { get; set; }
        public virtual klient klient { get; set; }
        public virtual sotrudniki sotrudniki { get; set; }
        public virtual uslugi uslugi { get; set; }
    }
}
